"use strict";

// All UI texts. You can translate whole UI by modifying these values.
module.exports = {
  ui: {
    newGame: "Új játék",
    endGame: "A játék véget ért!",
    throwDice: "Dobj",
    highScores: "Rekordok",
    ones: "Egyesek",
    twos: "Kettesek",
    threes: "Hármasok",
    fours: "Négyesek",
    fives: "Ötösök",
    sixes: "Hatosok",
    bonus: "Bónusz",
    onePair: "1 Pár",
    twoPairs: "2 Pár",
    threeOfAKind: "Drill",threeOfAKindSmall: "(3 egyforma)",
    fourOfAKind: "Póker",fourOfAKindSmall: "(4 egyforma)",
    smallStraight: "Kis sor",smallStraightSmall: "(1,2,3,4,5)",
    largeStraight: "Nagy sor",largeStraightSmall:"(2,3,4,5,6)",
    fullHouse: "Full", fullHouseSmall: "(2+3 egyforma)",
    chance: "Chance",chanceSmall:"(tetszőleges)",
    yatzy: "Nagy póker",yatzySmall:"(5 egyforma)",
    combination: "Kombináció",
    score: "Pontszám",
    total: "Összesen",
    back: "Vissza",
    round: "Kör",
    throwRound: "Dobás",
    player1Name: "1. Játékos Neve",
    player2Name: "2. Játékos Neve",
    player3Name: "3. Játékos Neve",
    player4Name: "4. Játékos Neve",
    player1Type: "1. Játékos típusa",
    player2Type: "2. Játékos típusa",
    player3Type: "3. Játékos típusa",
    player4Type: "4. Játékos típusa",
    player: "Játékos",
    winner: "Nyertes:",
    numberOfPlayers: "Játékosok száma",
    select: "Választás",
    totalRounds: 15,
    totalThrows: 3,
    human: "Személy",
    ai: "AI",
    ai_real_name: "KAI",
    ai_message_1: "Kis türelmet... KAI új kört kezd",
    ai_message_2: "Kis türelmet... KAI éppen dob",
    ai_message_3: "Kis türelmet... KAI kiválasztja melyik kockával dob újra",
    ai_message_4: "Kis türelmet... KAI választása"
  }
};
